#!groovy

// Generated by IBM TransformationAdvisor
// Mon Feb 04 16:29:20 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}